name: 📦 - Publish Documentation with GitHub Pages
on:
  release:
    types: [created]

jobs:
  publish-release:
    name: Publish Release Documentation
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages      

      - id: refresh-gh-pages
        name: "Refresh Doc Branch"
        run: |
          git pull --rebase origin ${{ github.event.release.tag_name }}
          git push origin gh-pages          
          


